package ru.solovetskyJungs.museum.entities;

public enum ArtifactType {
    UNDEFINED,
    PAINTING,
    GRAPHICS,
    SCULPTURE,
    APPLIED_ART,
    NUMISMATICS,
    ARCHAEOLOGY,
    RARE_BOOKS,
    WEAPON,
    DOCUMENTS,
    PHOTOGRAPHS,
    NATURAL_SCIENCE_COLLECTION,
    MINERAL_COLLECTION,
    TECHNOLOGY,
    PRINTED_PRODUCTS,
    OTHER
}
